BookReader/Controllers/AuthorController.cs
using BookReader.BLL;
using BookReader.Models;
using System;
using System.Web.Mvc;

namespace BookReader.Controllers
{
    public class AuthorController : Controller
    {
        public AuthorBLL authorBLL;
        public GenreBLL genreBLL;
        public BookContext bookContext;


        public AuthorController()
        {
            authorBLL = new AuthorBLL();
            genreBLL = new GenreBLL();
            bookContext = new BookContext();
        }
        // GET: Author
        public ActionResult Index(Author author)
        {
            GenreBLL genreBLL = new GenreBLL();
            ViewBag.Genre = genreBLL.List();

            return View(authorBLL.IList());
        }

        public ActionResult RegisterAuthor(Author author)
        {
            GenreBLL genreBLL = new GenreBLL();
            ViewBag.Genre = genreBLL.List();

            return View("Register", author);
        }

        public ActionResult AddAuthor(Author author)
        {
            if (ModelState.IsValid)
            {
                authorBLL.Add(author);
                return RedirectToAction("Index");

            }
            else
            {
                return View("Index", author);
            }
        }
        public void RemoveAuthor(string id)
        {
            AuthorBLL author = new AuthorBLL();
            author.Remove(id);
        }
        public void UpdateAuthor(int id, string name, int idGenre,string mainSaga,string favoriteBook, DateTime date)
        {
            AuthorBLL authorBLL = new AuthorBLL();
            Author author = new Author();
            author.Id = id;
            author.Name = name;
            author.IdGenre = idGenre;
            author.MainSaga = mainSaga;
            author.FavoriteBook = favoriteBook;
            author.DateCreate = date;

            authorBLL.Update(author);
        }

    }
}

BookReader/Controllers/BookController.cs
using BookReader.BLL;
using BookReader.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Web.Mvc;

namespace BookReader.Controllers
{
    public class BookController : Controller
    {
        private BookBLL bookBLL;

        public BookController(BookBLL bookBLL)
        {
            this.bookBLL = bookBLL;
        }

        // GET: Book
        public ActionResult Register(Book book)
        {
            ViewBag.listaAut = bookBLL.ListAuthors();
            ViewBag.listaGen = bookBLL.ListGenres();


            return View("Register", book);
        }

        public ActionResult Index(Book book)
        {
            return View();
        }
        public JArray GetBook()
        {
            BookBLL bookBLL = new BookBLL();

            return bookBLL.GetBook();
        }

        public ActionResult AddBook(FormCollection form)
        {
            BookBLL bookBLL = new BookBLL();

            Book book = new Book
            {
                Name = Request.Form["Name"],
                IdAuthor = int.Parse(Request.Form["IdAut"]),
                IdGenre = int.Parse(Request.Form["IdGen"]),
                Indication = Request.Form["Indication"],
                Saga = Request.Form["Saga"],
                DateCreate = DateTime.Today

            };

            bookBLL.AddBook(book);

            return RedirectToAction("Index");

        }

        public ActionResult AddBookRead(int id, string resume, DateTime start, DateTime end)
        {
            BookReadBLL bookBLL = new BookReadBLL();

            bookBLL.AddBookRead(id, resume, start, end);

            return RedirectToAction("./View/BookRead/Index");
        }

        public void RemoveBook(string id)
        {
            BookBLL bookBLL = new BookBLL();
            bookBLL.Remove(id);

        }
        public string DetailsBook(int id)
        {
            BookBLL bookBLL = new BookBLL();

            return bookBLL.DetailsBook(id).ToString();
        }
        public ActionResult UpdBook(int id,string name, string indication, string saga, string resume, DateTime start, DateTime end)
        {
            BookBLL bookBLL = new BookBLL();
            Book book = new Book()
            {
                Id = id,
                Name = name,
                Indication = indication,
                Saga = saga
            };

            BookRead bookRead = new BookRead() { 
                IdBK = id,
                Resume = resume,
                DateStart = start,
                DateEnd = end
            };

            bookBLL.UpdBook(book, bookRead);

            return RedirectToAction("./View/BookRead/Index");
        }
        public ActionResult UpdBook(int id, string name, string indication, string saga)
        {
            BookBLL bookBLL = new BookBLL();
            Book book = new Book()
            {
                Id = id,
                Name = name,
                Indication = indication,
                Saga = saga
            };
            //bookBLL.UpdBook(book, bookRead);

            return RedirectToAction("./View/BookRead/Index");
        }
    }
}

BookReader/Controllers/BookReadController.cs
using BookReader.BLL;
using System.Web.Mvc;

namespace BookReader.Controllers
{
    public class BookReadController : Controller
    {
        private BookReadBLL bookReadBLL;
        // GET: BookRead
        public BookReadController(BookReadBLL bookReadBLL)
        {
            this.bookReadBLL = bookReadBLL;
        }

        public ActionResult Index()
        {
            return View(bookReadBLL.List());
        }
    }
}

BookReader/Controllers/GenreController.cs
using BookReader.BLL;
using BookReader.Models;
using System;
using System.Web.Mvc;

namespace BookReader.Controllers
{
    public class GenreController : Controller
    {
        private GenreBLL genreBLL;

        public GenreController(GenreBLL genreBLL)
        {
            this.genreBLL = genreBLL;
        }
        // GET: Genre
        public ActionResult Index(Genre genre)
        {
            return View(genreBLL.List());
        }
        public ActionResult Register(Genre genre)
        {
            return View(genre);
        }

        public ActionResult AddGenre(Genre genre)
        {
            if (ModelState.IsValid)
            {
                genreBLL.Add(genre);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Register", genre);
            }
        }
        public void RemoveGenre(string id)
        {
            GenreBLL genreBLL = new GenreBLL();
            genreBLL.Remove(id);
        }
        public void UpdateGenre(int id,string name, string description, DateTime date)
        {
            GenreBLL genreBLL = new GenreBLL();
            Genre genre = new Genre();
            genre.Id = id;
            genre.Name = name;
            genre.Description = description;
            genre.DateCreate = date;
            genreBLL.Update(genre);
        }
    }
}

BookReader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/modernizr")

    @*@Styles.Render("~/Style/css")

        @Styles.Render("~/Style/css/site.css")*@

    <link rel="stylesheet" type="text/css" href="~/Style/css/bootstrap.css" />
    
    <link rel="stylesheet" type="text/css" href="~/Style/css/site.css" />

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap5.min.css">

    <link rel="stylesheet" type="text/css" href="~/Style/css/jquery.dataTables.css">

    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap5.min.js"></script>

    @Scripts.Render("~/Scripts/jquery.maskedinput.min.js")



</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookReader", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Generos", "Index", "Genre")</li>
                    <li>@Html.ActionLink("Autor", "Index", "Author")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Livros</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Livros Cadastrados", "Index", "Book")</li>
                            <li>@Html.ActionLink("Livros Lidos", "Index", "BookRead")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Desenvolvido Por Matheus Veiga</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>